// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxcnlzeeheafepavmbcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4Y25semVlaGVhZmVwYXZtYmNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMTYyODgsImV4cCI6MjA1NjY5MjI4OH0.t6ySqS5E-nZtiAQNnUY4vQes3DzM7zJ81fKfVDzHcMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);